### ISSUE TITLE
기능 확대 제안사항~

### ISSUE THREAD

**Issue by soclic** [ultrakeypoint/commute-record#10]
1. 반차 / 월차 / 휴가 관련 추가 UI 지원 가능할까용? 쉬는날은 중대사항이지 ㄹㅇㅋㅋ
2. 메모 내용에 대한 템플릿 기능 추가 검토 가능할까요? 일정 기간 동일한 메모내용을 연달아 입력해야 할 때가 있음.
제안 초안) 
예를들면, 5월 10일 ~ 5월 15일 : 센터파견지원 일때 매일 똑같은 메모내용 하나씩 추가하기 귀찮을거가틈
기본 메모 설정값이야 빈값일거고, 
새 row생길때 (프로그램 접속 타이밍에 + 기존 데이터에 동일 날짜 row가 없는 경우 같은데 맞나여?)
해당 시점 한정 메모 초기값 지정기능같은느낌으루다가

뱀발) 이 프로그램 그래서 이름이 먼가요 설마 출/퇴근 일지? commute-record?

**Comment by ultrakeypoint** [comment]
확인중입니다.

**Comment by ultrakeypoint** [comment]
The fix has been completed, please check it in the next version.

1. Korean Full Title : 출/퇴근 일지
2. English Full Title : Commute Record
