### ISSUE TITLE
이슈 보고

### ISSUE THREAD

**Issue by yucosmosme** [ultrakeypoint/commute-record#12]
1. 날짜 저장했는데 며칠 뒤에 켰을 때 날짜가 사라짐 -> DB에 잘못된 날짜로 저장되어 있었음. 제대로 바꾸니까 다시 보임
2. 까먹고 출퇴근 기록을 입력하지 않고 프로그램도 아예 실행을 하지 않은 경우 --> 이후의 날에 프로그램 실행 시 해당 날이 리스트에 보이지 않아서 추후 추가가 불가능 ---> 제안: 새로 프로그램 켰을 때 그 전에 앱 접속 안한 날 다 추가해버리기

**Comment by ultrakeypoint** [comment]
확인중입니다

**Comment by ultrakeypoint** [comment]
The fix has been completed, please check it in the next version.

1. Use remove button
![image](https://user-images.githubusercontent.com/73173310/225019870-62c51f02-2fd7-432e-815f-23ad498bafff.png)

2. Use add button
![image](https://user-images.githubusercontent.com/73173310/225019927-f31824fe-64ed-4402-98e4-9093da8d0d64.png)
