### ISSUE TITLE
프로그램 화면 크기 확대/축소 관련 피드백드립니당

### ISSUE THREAD

**Issue by soclic** [ultrakeypoint/commute-record#5]
화면 디자인이 '프로그램 실행 후 가장 큰 화면 사이즈' 기준이라서,

1. 프로그램 실행
2. 화면 최대화 or 크기조정(크게) 
3. 화면 창 크기 작게 변경 (원복 등)

이 경우, 3번 시점에도 2번 화면 크기가 기준이라 메모저장을 누를 수 없습니다.

![도움](https://user-images.githubusercontent.com/30066769/224202053-acb87b5b-b636-460d-ad7e-32c272af02af.png)

프로그램 재시작하면 되긴 하는디...................

**Comment by ultrakeypoint** [comment]
확인중입니다.

**Comment by ultrakeypoint** [comment]
The fix has been completed, please check it in the next version.
